import type { FrontCardData } from 'yugioh-card'
import { PATH } from '../config'

export default {
  language: 'tc',
  font: 'custom2',
  name: '選舉很簡單',
  color: '',
  align: 'left',
  gradient: false,
  gradientColor1: '#999999',
  gradientColor2: '#ffffff',
  type: 'spell',
  attribute: '',
  icon: 'quick-play',
  image: `${PATH.YUGIOH_RESOURCES_DIR}/korea-fish.jpg`,
  cardType: 'normal',
  pendulumType: 'normal-pendulum',
  level: 0,
  rank: 0,
  pendulumScale: 0,
  pendulumDescription: '',
  monsterType: '',
  atkBar: true,
  atk: 0,
  def: 0,
  arrowList: [],
  description: '票多的贏，票少的輸',
  firstLineCompress: false,
  descriptionAlign: false,
  descriptionZoom: 1,
  descriptionWeight: 0,
  package: 'SD25-SC001',
  password: '',
  copyright: 'jp',
  laser: '',
  rare: '',
  twentieth: false,
  radius: true,
  scale: 1,
} as FrontCardData
