import type { FrontCardData } from 'yugioh-card'

export default {
  language: 'tc',
  font: 'custom2',
  name: '青眼白龍',
  color: '',
  align: 'left',
  gradient: false,
  gradientColor1: '#999999',
  gradientColor2: '#ffffff',
  type: 'monster',
  attribute: 'light',
  icon: '',
  image: '',
  cardType: 'normal',
  pendulumType: 'normal-pendulum',
  level: 8,
  rank: 0,
  pendulumScale: 0,
  pendulumDescription: '',
  monsterType: '龍族/通常',
  atkBar: true,
  atk: 3000,
  def: 2500,
  arrowList: [],
  description: '以高攻擊力著稱的傳說之龍。任何對手都能將之粉碎，其破壞力不可估量。',
  firstLineCompress: false,
  descriptionAlign: false,
  descriptionZoom: 1,
  descriptionWeight: 0,
  package: '',
  password: '89631139',
  copyright: 'jp',
  laser: '',
  rare: '',
  twentieth: false,
  radius: true,
  scale: 1,
} as FrontCardData
